markdown: kramdown
pygments: true
url: http://blog.franciscopinto.me
title: Francisco Pinto
author: Francisco Pinto
description: "Engineer, proud dad, Apple enthusiast, tech and cinnamon tea lover. Sometimes I design stuff that works."
production_url : http://blog.franciscopinto.me
simple_search: http://www.duckduckgo.com/