markdown: kramdown
title: Francisco Pinto
description: "Thoughts on life, software development, Macs and technlogy."
simple_search: http://www.duckduckgo.com/
author :
  name : Francisco Pinto
  github : francisjpo
  twitter : francisjpo
